version: '2'

services:

    postgres-dev:
        image: postgres
        restart: always
        ports:
            - 15432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    postgres-unittest:
        image: postgres
        restart: always
        ports:
            - 25432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
