spring:
  profiles:
    active: development
    
databaseConfig:
  databases: []
  retryDelay: 60000
  dropAllowed: false
  schemaListingAllowed: false
  cooldownMonths: 6

metrics:
  resourceUseCollectInterval: "300000"

logging:
  level:
    no.skatteetaten.aurora: DEBUG
    no.skatteetaten.aurora.filter: INFO
    no.skatteetaten.aurora.databasehotell.DbhConfigurator: WARN
    com.zaxxer.hikari: WARN
    org:
      springframework: WARN
      apache:
        catalina: WARN

aurora:
  authenticationEnabled: true
  token:
    headerValuePrefix: aurora-token

---
spring:
  profiles: development

databaseConfig:
  dropAllowed: true
  schemaListingAllowed: true
  defaultInstanceName: "${dbh.dev.db.instanceName:dev}"
  databases:
  - host: "${dbh.dev.db.host:localhost}"
    service: "${dbh.dev.db.service:dbhotel}"
    instanceName: "${dbh.dev.db.instanceName:dev}"
    createSchemaAllowed: "${dbh.dev.db.createSchemaAllowed:true}"
    username: "${dbh.dev.db.username:aos_api_user as sysdba}"
    password: "${dbh.dev.db.password:dbh}"
    clientService: "${dbh.dev.db.clientService:dbhotel}"
    oracleScriptRequired: "${dbh.dev.db.oracleScriptRequired:true}"

aurora:
  authenticationEnabled: false
  token:
    location: ./src/test/resources/aurora-token

---
spring:
  profiles: openshift

aurora:
  token:
    location: /u01/secrets/app/aurora-token/token