spring:
  profiles:
    active: development
    
database-config:
  databases: []
  retryDelay: 60000
  dropAllowed: false
  schemaListingAllowed: false
  cooldownDaysAfterDelete: 30

management:
  metrics:
    distribution:
      maximum-expected-value:
        http: 100ms
      minimum-expected-value:
        http: 100ms
      sla:
        http: 100ms,500ms,1s,2s,3s,5s,10s,15s,25s

metrics:
  resourceUseCollectInterval: "300000"

logging:
  level:
    no.skatteetaten.aurora: INFO
    no.skatteetaten.aurora.databasehotel.DbhConfigurator: WARN
    no.skatteetaten.aurora.databasehotel.service.DatabaseHotelService: DEBUG
    no.skatteetaten.aurora.databasehotel.service.ExternalSchemaManager: DEBUG


    com.zaxxer.hikari: WARN
    org:
      springframework: WARN
      apache:
        catalina: WARN

aurora:
  authentication:
      enabled: true
  token:
    header-value-prefix: aurora-token | bearer

---
spring:
  profiles: development

database-config:
  dropAllowed: true
  schemaListingAllowed: true
  defaultInstanceName: "${dbh.dev.db.instanceName:dev-postgres}"
  databases:
  - host: "${dbh.dev.db.oracle.host:localhost}"
    engine: "${dbh.dev.db.oracle.engine:oracle}"
    service: "${dbh.dev.db.oracle.service:dbhotel}"
    instanceName: "${dbh.dev.db.oracle.instanceName:dev-oracle}"
    createSchemaAllowed: "${dbh.dev.db.oracle.createSchemaAllowed:true}"
    username: "${dbh.dev.db.oracle.username:aos_api_user as sysdba}"
    password: "${dbh.dev.db.oracle.password:dbh}"
    clientService: "${dbh.dev.db.oracle.clientService:dbhotel}"
    oracleScriptRequired: "${dbh.dev.db.oracle.oracleScriptRequired:true}"
  - host: localhost
    port: 15432
    engine: postgres
    instanceName: dev-postgres
    createSchemaAllowed: true
    username: postgres
    password: postgres
    labels:
        affiliation: aurora
        type: dev

metrics:
    resourceUseCollectInterval: "10000"

aurora:
  authentication:
      enabled: false
  token:
    location: ./src/test/resources/aurora-token

---
spring:
  profiles: openshift

aurora:
  token:
    location: /u01/secrets/app/aurora-token/token
