spring:
  profiles:
    active: development
    
database-config:
  databases: []
  retryDelay: 60000
  dropAllowed: false
  schemaListingAllowed: false
  cooldownMonths: 6

metrics:
  resourceUseCollectInterval: "300000"

logging:
  level:
    no.skatteetaten.aurora: DEBUG
    no.skatteetaten.aurora.filter: INFO
    no.skatteetaten.aurora.databasehotell.DbhConfigurator: WARN
    com.zaxxer.hikari: WARN
    org:
      springframework: WARN
      apache:
        catalina: WARN

aurora:
  authenticationEnabled: true
  token:
    headerValuePrefix: aurora-token

---
spring:
  profiles: development

database-config:
  dropAllowed: true
  schemaListingAllowed: true
  defaultInstanceName: "${dbh.dev.db.instanceName:dev-postgres}"
  databases:
  - host: "${dbh.dev.db.oracle.host:localhost}"
    engine: "${dbh.dev.db.oracle.engine:oracle}"
    service: "${dbh.dev.db.oracle.service:dbhotel}"
    instanceName: "${dbh.dev.db.oracle.instanceName:dev-oracle}"
    createSchemaAllowed: "${dbh.dev.db.oracle.createSchemaAllowed:true}"
    username: "${dbh.dev.db.oracle.username:aos_api_user as sysdba}"
    password: "${dbh.dev.db.oracle.password:dbh}"
    clientService: "${dbh.dev.db.oracle.clientService:dbhotel}"
    oracleScriptRequired: "${dbh.dev.db.oracle.oracleScriptRequired:true}"
  - host: "${dbh.dev.db.postgres.host:localhost}"
    engine: "${dbh.dev.db.postgres.engine:postgres}"
    instanceName: "${dbh.dev.db.postgres.instanceName:dev-postgres}"
    createSchemaAllowed: "${dbh.dev.db.postgres.createSchemaAllowed:true}"
    username: "${dbh.dev.db.postgres.username:aos_api_user as sysdba}"
    password: "${dbh.dev.db.postgres.password:dbh}"

aurora:
  authenticationEnabled: false
  token:
    location: ./src/test/resources/aurora-token

---
spring:
  profiles: openshift

aurora:
  token:
    location: /u01/secrets/app/aurora-token/token