CREATE TABLE LABELS (
  id VARCHAR2(255) NOT NULL,
  schema_id VARCHAR2(255) NOT NULL,
  name VARCHAR2(4000) NOT NULL,
  value VARCHAR2(4000) NOT NULL
);
ALTER TABLE LABELS ADD CONSTRAINT UNIQUE_NAME_PR_SCHEMA UNIQUE(schema_id, name);