grant select on DATABASEHOTEL_INSTANCE_DATA.EXTERNAL_SCHEMA to AOS_API_USER;
grant select on DATABASEHOTEL_INSTANCE_DATA.LABELS to AOS_API_USER;
grant select on DATABASEHOTEL_INSTANCE_DATA.USERS to AOS_API_USER;
