ALTER TABLE DATABASEHOTEL_INSTANCE_DATA.SCHEMA_DATA ADD CREATED_DATE TIMESTAMP;
UPDATE DATABASEHOTEL_INSTANCE_DATA.schema_data sd SET CREATED_DATE = (SELECT created FROM dba_users u WHERE sd.NAME = u.USERNAME);
